[[plugins]]
package = "netlify-plugin-cache"
  [plugins.inputs]
  paths = [ ".cache" ]


[[headers]]
    for = "/*"
    [headers.values]
    Content-Security-Policy = "upgrade-insecure-requests; block-all-mixed-content;"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "autoplay=(), camera=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), publickey-credentials-get=()"


[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/subscribe"
  to = "https://cybercultural.com/donate/"
  status = 301

[[redirects]]
  from = "/p/audiobooks-deep-dive-latest-statistics"
  to = "https://cybercultural.ricmac.org/p/audiobooks-deep-dive-latest-statistics/"
  status = 301

[[redirects]]
  from = "/p/introducing-cybercultural"
  to = "https://cybercultural.ricmac.org/p/introducing-cybercultural/"
  status = 301

[[redirects]]
  from = "p/spotify-and-google-make-moves-in"
  to = "https://cybercultural.ricmac.org/p/spotify-and-google-make-moves-in/"
  status = 301

[[redirects]]
  from = "/p/whats-new-in-online-ticketing-cybercultural"
  to = "https://cybercultural.ricmac.org/p/whats-new-in-online-ticketing-cybercultural/"
  status = 301

[[redirects]]
  from = "/p/wattpads-hollywood-formula-cybercultural"
  to = "https://cybercultural.ricmac.org/p/wattpads-hollywood-formula-cybercultural/"
  status = 301

[[redirects]]
  from = "/p/beyond-music-distribution-cybercultural"
  to = "https://cybercultural.ricmac.org/p/beyond-music-distribution-cybercultural/"
  status = 301

[[redirects]]
  from = "/p/audiobooks-continue-strong-growth"
  to = "https://cybercultural.ricmac.org/p/audiobooks-continue-strong-growth/"
  status = 301

[[redirects]]
  from = "/p/espn-airballs-its-nba-live-stream"
  to = "https://cybercultural.ricmac.org/p/espn-airballs-its-nba-live-stream/"
  status = 301

[[redirects]]
  from = "/p/digital-first-instagram-first-for"
  to = "https://cybercultural.ricmac.org/p/digital-first-instagram-first-for/"
  status = 301

[[redirects]]
  from = "/p/is-crowdfunding-really-a-viable-business"
  to = "https://cybercultural.ricmac.org/p/is-crowdfunding-really-a-viable-business/"
  status = 301

[[redirects]]
  from = "/p/the-marketing-upside-of-streaming"
  to = "https://cybercultural.ricmac.org/p/the-marketing-upside-of-streaming/"
  status = 301

[[redirects]]
  from = "/p/the-chernobyl-podcast-and-the-value"
  to = "https://cybercultural.ricmac.org/p/the-chernobyl-podcast-and-the-value/"
  status = 301

[[redirects]]
  from = "/p/interview-with-believe-cco-jonathan"
  to = "https://cybercultural.ricmac.org/p/interview-with-believe-cco-jonathan/"
  status = 301

[[redirects]]
  from = "/p/how-photo-sharing-is-impacting-the"
  to = "https://cybercultural.ricmac.org/p/how-photo-sharing-is-impacting-the/"
  status = 301

[[redirects]]
  from = "/p/what-facebooks-libra-means-for-spotify"
  to = "https://cybercultural.ricmac.org/p/what-facebooks-libra-means-for-spotify/"
  status = 301

[[redirects]]
  from = "/p/ai-in-the-cultural-industries-uses"
  to = "https://cybercultural.ricmac.org/p/ai-in-the-cultural-industries-uses/"
  status = 301

[[redirects]]
  from = "/p/quick-reader-survey"
  to = "https://cybercultural.ricmac.org/p/quick-reader-survey/"
  status = 301

[[redirects]]
  from = "/p/cybercultural-update-survey-results"
  to = "hhttps://cybercultural.ricmac.org/p/cybercultural-update-survey-results/"
  status = 301

[[redirects]]
  from = "/p/what-youtube-originals-pivot-tells"
  to = "https://cybercultural.ricmac.org/p/what-youtube-originals-pivot-tells/"
  status = 301

[[redirects]]
  from = "/p/the-micropayments-market"
  to = "https://cybercultural.ricmac.org/p/the-micropayments-market/"
  status = 301

[[redirects]]
  from = "/p/taking-on-internet-platform-bullies"
  to = "https://cybercultural.ricmac.org/p/taking-on-internet-platform-bullies/"
  status = 301

[[redirects]]
  from = "/p/adapting-to-the-post-print-world"
  to = "https://cybercultural.ricmac.org/p/adapting-to-the-post-print-world/"
  status = 301

[[redirects]]
  from = "/p/exclusive-data-online-gaming-habits"
  to = "https://cybercultural.ricmac.org/p/exclusive-data-online-gaming-habits/"
  status = 301

[[redirects]]
  from = "/p/nearly-extinct-pop-culture-activities"
  to = "https://cybercultural.ricmac.org/p/nearly-extinct-pop-culture-activities/"
  status = 301

[[redirects]]
  from = "/p/cybercultural-update-launching-paid"
  to = "https://cybercultural.ricmac.org/p/cybercultural-update-launching-paid/"
  status = 301

[[redirects]]
  from = "/p/facebook-svod-google-podcast-search"
  to = "https://cybercultural.ricmac.org/p/facebook-svod-google-podcast-search/"
  status = 301

[[redirects]]
  from = "/p/amazon-publishing-muscle-netflix"
  to = "https://cybercultural.ricmac.org/p/amazon-publishing-muscle-netflix/"
  status = 301

[[redirects]]
  from = "/p/are-we-doing-enough-to-archive-digital"
  to = "https://cybercultural.ricmac.org/p/are-we-doing-enough-to-archive-digital/"
  status = 301

[[redirects]]
  from = "/p/tumblr-thoughts-the-future-of-social"
  to = "https://cybercultural.ricmac.org/p/tumblr-thoughts-the-future-of-social/"
  status = 301

[[redirects]]
  from = "/p/ai-in-magazines-youtube-copyright"
  to = "https://cybercultural.ricmac.org/p/ai-in-magazines-youtube-copyright/"
  status = 301

[[redirects]]
  from = "/p/how-interactive-media-fits-into-the"
  to = "https://cybercultural.ricmac.org/p/how-interactive-media-fits-into-the/"
  status = 301

[[redirects]]
  from = "/p/immersive-music-future-of-movie-making"
  to = "https://cybercultural.ricmac.org/p/immersive-music-future-of-movie-making/"
  status = 301

[[redirects]]
  from = "/p/hasbro-tupac-netflix-human-curators"
  to = "https://cybercultural.ricmac.org/p/hasbro-tupac-netflix-human-curators/"
  status = 301

[[redirects]]
  from = "/p/revenue-challenges-in-subscription"
  to = "https://cybercultural.ricmac.org/p/revenue-challenges-in-subscription/"
  status = 301

[[redirects]]
  from = "/p/alternatives-to-spotify-for-x-subscription"
  to = "https://cybercultural.ricmac.org/p/alternatives-to-spotify-for-x-subscription/"
  status = 301

[[redirects]]
  from = "/p/virtual-beings-cyberpunk-keanu-ai"
  to = "https://cybercultural.ricmac.org/p/virtual-beings-cyberpunk-keanu-ai/"
  status = 301

[[redirects]]
  from = "/p/how-blogs-newsletters-and-tumblr"
  to = "https://cybercultural.ricmac.org/p/how-blogs-newsletters-and-tumblr/"
  status = 301

[[redirects]]
  from = "/p/media-paywalls-and-micropayments"
  to = "https://cybercultural.ricmac.org/p/media-paywalls-and-micropayments/"
  status = 301

[[redirects]]
  from = "/p/4-cultural-products-in-various-stages"
  to = "https://cybercultural.ricmac.org/p/4-cultural-products-in-various-stages/"
  status = 301

[[redirects]]
  from = "/p/bowie-houdini-and-other-reasons-i"
  to = "https://cybercultural.ricmac.org/p/bowie-houdini-and-other-reasons-i/"
  status = 301

[[redirects]]
  from = "/p/apple-culture-tech-news-the-rise"
  to = "https://cybercultural.ricmac.org/p/apple-culture-tech-news-the-rise/"
  status = 301

[[redirects]]
  from = "/p/weekly-wrap-up-7-13-sep-19"
  to = "https://cybercultural.ricmac.org/p/weekly-wrap-up-7-13-sep-19/"
  status = 301

[[redirects]]
  from = "/p/peak-tv-vevo-vs-spotify-bjrk-vr-ebook"
  to = "https://cybercultural.ricmac.org/p/peak-tv-vevo-vs-spotify-bjrk-vr-ebook/"
  status = 301

[[redirects]]
  from = "/p/exclusive-data-email-newsletters"
  to = "https://cybercultural.ricmac.org/p/exclusive-data-email-newsletters/"  

[[redirects]]
  from = "/p/new-washington-post-ad-network-and"
  to = "https://cybercultural.ricmac.org/p/new-washington-post-ad-network-and/"  

[[redirects]]
  from = "/p/weekly-wrap-up-14-20-sep-2019"
  to = "https://cybercultural.ricmac.org/p/weekly-wrap-up-14-20-sep-2019/"  

[[redirects]]
  from = "/p/facebook-portal-pop-music-pressures"
  to = "https://cybercultural.ricmac.org/p/facebook-portal-pop-music-pressures/"  

[[redirects]]
  from = "/p/spotify-upgrades-artist-app-espn"
  to = "https://cybercultural.ricmac.org/p/spotify-upgrades-artist-app-espn/"  

[[redirects]]
  from = "/p/audio-vs-text-the-rise-of-podcasts"
  to = "https://cybercultural.ricmac.org/p/audio-vs-text-the-rise-of-podcasts/"  

[[redirects]]
  from = "/p/weekly-wrap-up-21-27-sep-2019"
  to = "https://cybercultural.ricmac.org/p/weekly-wrap-up-21-27-sep-2019/"  

[[redirects]]
  from = "/p/food52-ny-magazine-online-advertising"
  to = "https://cybercultural.ricmac.org/p/food52-ny-magazine-online-advertising/"  

[[redirects]]
  from = "/p/fortnite-revenue-dip-comics-in-streaming"
  to = "https://cybercultural.ricmac.org/p/fortnite-revenue-dip-comics-in-streaming/"  

[[redirects]]
  from = "/p/weekly-wrap-up-28-sep-4-oct-19"
  to = "https://cybercultural.ricmac.org/p/weekly-wrap-up-28-sep-4-oct-19/"  

[[redirects]]
  from = "/p/sports-illustrated-debacle-reading"
  to = "https://cybercultural.ricmac.org/p/sports-illustrated-debacle-reading/"  

[[redirects]]
  from = "/p/the-state-of-podcasting"
  to = "https://cybercultural.ricmac.org/p/the-state-of-podcasting/"  

[[redirects]]
  from = "/p/radio-tsl-spotify-daily-drive-remembering"
  to = "https://cybercultural.ricmac.org/p/radio-tsl-spotify-daily-drive-remembering/"  

[[redirects]]
  from = "/p/netflix-for-kids-spotify-canvas-audius"
  to = "https://cybercultural.ricmac.org/p/netflix-for-kids-spotify-canvas-audius/"  

[[redirects]]
  from = "/p/change-to-cybercultural-subscriptions"
  to = "https://cybercultural.ricmac.org/p/change-to-cybercultural-subscriptions/"  

[[redirects]]
  from = "/p/why-the-next-wave-of-digital-media"
  to = "https://cybercultural.ricmac.org/p/why-the-next-wave-of-digital-media/"  

[[redirects]]
  from = "/p/how-the-internet-is-changing-cultural"
  to = "https://cybercultural.ricmac.org/p/how-the-internet-is-changing-cultural/"  

[[redirects]]
  from = "/p/re-inventing-20th-century-culture"
  to = "https://cybercultural.ricmac.org/p/re-inventing-20th-century-culture/"  

[[redirects]]
  from = "/p/when-digital-is-blended-with-reality"
  to = "https://cybercultural.ricmac.org/p/when-digital-is-blended-with-reality/"  

[[redirects]]
  from = "/p/the-long-tail-has-failed-the-cultural"
  to = "https://cybercultural.ricmac.org/p/the-long-tail-has-failed-the-cultural/"  

[[redirects]]
  from = "/p/top-5-culture-tech-trends-of-2019"
  to = "https://cybercultural.ricmac.org/p/top-5-culture-tech-trends-of-2019/"  

[[redirects]]
  from = "/p/the-decade-in-culture-tech-streaming"
  to = "https://cybercultural.ricmac.org/p/the-decade-in-culture-tech-streaming/"  

[[redirects]]
  from = "/p/culture-tech-notes-2020-book-project"
  to = "https://cybercultural.ricmac.org/p/culture-tech-notes-2020-book-project/"  

[[redirects]]
  from = "/p/from-internet-amnesia-to-holographic"
  to = "https://cybercultural.ricmac.org/p/from-internet-amnesia-to-holographic/"  

[[redirects]]
  from = "/p/resurrecting-cybercultural"
  to = "https://cybercultural.ricmac.org/p/resurrecting-cybercultural/"  

[[redirects]]
  from = "/p/metaverse-hype-or-reality"
  to = "https://cybercultural.ricmac.org/p/metaverse-hype-or-reality/"  

[[redirects]]
  from = "/p/my-top-internet-tech-of-2021"
  to = "https://cybercultural.ricmac.org/p/my-top-internet-tech-of-2021/"    

[[redirects]]
  from = "/p/top-internet-tech-stories-of-2021"
  to = "https://cybercultural.ricmac.org/p/top-internet-tech-stories-of-2021/"  

[[redirects]]
  from = "/p/social-networking-past-present-and"
  to = "https://cybercultural.ricmac.org/p/social-networking-past-present-and/"    

[[redirects]]
  from = "/p/nft-iphonelaunch-bowie"
  to = "https://cybercultural.ricmac.org/p/nft-iphonelaunch-bowie/"  

[[redirects]]
  from = "/p/twitter-nft-microsoft-activision"
  to = "https://cybercultural.ricmac.org/p/twitter-nft-microsoft-activision/"    

[[redirects]]
  from = "/p/looking-at-web3-through-a-cultural"
  to = "https://cybercultural.ricmac.org/p/looking-at-web3-through-a-cultural/"  

[[redirects]]
  from = "/p/loneliness"
  to = "https://cybercultural.ricmac.org/p/loneliness/"    

[[redirects]]
  from = "/p/mobile-internet"
  to = "https://cybercultural.ricmac.org/p/mobile-internet/"  

[[redirects]]
  from = "/s/memoir"
  to = "/memoir"  

[[redirects]]
  from = "/s/culture-tech"
  to = "/articles"  

[[redirects]]
  from = "/s/tech-history"
  to = "/" 

[[redirects]]
  from = "/archive"
  to = "/"